name: Deploy project

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🟢 Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: 📦 Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 📦 Install dependencies
        run: yarn install

      - name: 📚 Build project
        run: yarn generate

      - name: 📋 Create not found page
        run: cp docs/index.html docs/404.html

      - name: 🚀 Deploy to GitHub Pages
        uses: wow-actions/update-file@v1
        with:
          path: docs/index.html
          content: deploy system
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
